function thresholdNames = THRESHOLD_NAMES()
%THRESHOLD_NAMES Returns all threshold names used by the tsad platform

thresholdNames = ["best_pointwise_f1_score", ...
                  "best_eventwise_f1_score", ...
                  "best_pointadjusted_f1_score", ...
                  "best_composite_f1_score", ...
                  "top_k", ...
                  "dynamic", ...
                  "gauss", ...
                  "gauss_train", ...
                  "max_train"];
end