datasetPath = "C:\Ich\Studium\Bachelorarbeit\Inhalt\Git\tsad_platform_parallel_dev\tsad_platform\datasets\OtherDatasets\Univariate\Semisupervised_NASA-SMAP";
configFileName = "config_small.json";
useFraction = 0.01;
preprocMethod = 'rescale';
ratioTestVal = 1;
thresholds = ["bestFscoreWeighted", ...
    "topK", ...
    "meanStd"];

thresholds_all = ["bestFscoreWeighted", ...
    "bestFscoreUnweighted", ...
    "bestFscoreEventwise", ...
    "bestFscoreComposite", ...
    "bestFscoreWeightedParametric", ...
    "bestFscoreUnweightedParametric", ...
    "bestFscoreEventwiseParametric", ...
    "bestFscoreCompositeParametric", ...
    "topK", ...
    "meanStd"];

evaluateAllForDataset(datasetPath, configFileName, useFraction, preprocMethod, ratioTestVal, thresholds);