function results = optimizeModel(optVars, models, trainingData, trainingLabels, testValData, testValLabels, testingData, testingLabels, thresholds, cmpScore, iterations, exportLogData)
rng default
optVariables = [];
optVarNames = fieldnames(optVars);
for i = 1:length(optVarNames)
    optVariables = [optVariables optimizableVariable(optVarNames{i}, ...
        optVars.(optVarNames{i}).value, 'Type', optVars.(optVarNames{i}).type)];
end

fun = @(x)opt_fun(models, ...
    trainingData, ...
    trainingLabels, ...
    testValData, ...
    testValLabels, ...
    testingData, ...
    testingLabels, ...
    thresholds, ...
    cmpScore, ...
    x, ...
    exportLogData);

results = bayesopt(fun, optVariables, Verbose=0,...
    AcquisitionFunctionName='expected-improvement-plus', ...
    MaxObjectiveEvaluations=iterations, ...
    IsObjectiveDeterministic=true);
end