function trainOptions = getOptionsForParallel(options, XVal, YVal, numWindows, dataqueue, idx)
switch options.model
    case 'FC AE'
        learningRate = 0.001;
        if options.hyperparameters.training.ratioTrainVal.value == 1
            trainOptions = trainingOptions('adam', ...
                'MaxEpochs', options.hyperparameters.training.epochs.value, ...
                'MiniBatchSize', options.hyperparameters.training.minibatchSize.value, ...
                'InitialLearnRate', learningRate, ...
                'Shuffle', 'every-epoch',...
                'OutputFcn', @(info) send(dataqueue, struct('experimentNumber', idx, 'info', info)));
        else
            trainOptions = trainingOptions('adam', ...
                'MaxEpochs', options.hyperparameters.training.epochs.value, ...
                'MiniBatchSize', options.hyperparameters.training.minibatchSize.value, ...
                'InitialLearnRate', learningRate, ...
                'ValidationData', {XVal, YVal}, ...
                'Shuffle', 'every-epoch',...
                'ValidationFrequency', floor(numWindows / (3 * options.hyperparameters.training.minibatchSize.value)), ...
                'OutputFcn', @(info) send(dataqueue, struct('experimentNumber', idx, 'info', info)));
        end
    case 'LSTM AE'
        learningRate = 0.001;
        if options.hyperparameters.training.ratioTrainVal.value == 1
            trainOptions = trainingOptions('adam', ...
                'MaxEpochs', options.hyperparameters.training.epochs.value, ...
                'MiniBatchSize', options.hyperparameters.training.minibatchSize.value, ...
                'InitialLearnRate', learningRate, ...
                'Shuffle', 'every-epoch',...
                'OutputFcn', @(info) send(dataqueue, struct('experimentNumber', idx, 'info', info)));
        else
            trainOptions = trainingOptions('adam', ...
                'MaxEpochs', options.hyperparameters.training.epochs.value, ...
                'MiniBatchSize', options.hyperparameters.training.minibatchSize.value, ...
                'InitialLearnRate', learningRate, ...
                'ValidationData', {XVal, YVal}, ...
                'Shuffle', 'every-epoch',...
                'ValidationFrequency', floor(numWindows / (3 * options.hyperparameters.training.minibatchSize.value)), ...
                'OutputFcn', @(info) send(dataqueue, struct('experimentNumber', idx, 'info', info)));
        end
    case 'Hybrid CNN-LSTM AE'
        learningRate = 0.001;
        if options.hyperparameters.training.ratioTrainVal.value == 1
            trainOptions = trainingOptions('adam', ...
                'MaxEpochs', options.hyperparameters.training.epochs.value, ...
                'GradientThreshold', 1, ...
                'InitialLearnRate', learningRate, ...
                'LearnRateSchedule', 'piecewise', ...
                'LearnRateDropPeriod', 96, ...
                'LearnRateDropFactor', 0.25, ...
                'MiniBatchSize', options.hyperparameters.training.minibatchSize.value,...
                'Verbose', false, ...
                'Shuffle', 'every-epoch',...
                'OutputFcn', @(info) send(dataqueue, struct('experimentNumber', idx, 'info', info)));
        else
            trainOptions = trainingOptions('adam', ...
                'MaxEpochs', options.hyperparameters.training.epochs.value, ...
                'GradientThreshold', 1, ...
                'InitialLearnRate', learningRate, ...
                'LearnRateSchedule', 'piecewise', ...
                'LearnRateDropPeriod', 96, ...
                'LearnRateDropFactor', 0.25, ...
                'MiniBatchSize', options.hyperparameters.training.minibatchSize.value,...
                'Verbose', false, ...
                'Shuffle', 'every-epoch',...
                'ValidationData', {XVal, YVal}, ...
                'ValidationFrequency', floor(numWindows / (3 * options.hyperparameters.training.minibatchSize.value)), ...
                'OutputFcn', @(info) send(dataqueue, struct('experimentNumber', idx, 'info', info)));
        end
    case 'TCN AE'
        learningRate = 0.001;
        if options.hyperparameters.training.ratioTrainVal.value == 1
            trainOptions = trainingOptions('adam', ...
                'MaxEpochs', options.hyperparameters.training.epochs.value, ...
                'MiniBatchSize', options.hyperparameters.training.minibatchSize.value, ...
                'InitialLearnRate', learningRate, ...
                'Shuffle', 'every-epoch',...
                'OutputFcn', @(info) send(dataqueue, struct('experimentNumber', idx, 'info', info)));
        else
            trainOptions = trainingOptions('adam', ...
                'MaxEpochs', options.hyperparameters.training.epochs.value, ...
                'MiniBatchSize', options.hyperparameters.training.minibatchSize.value, ...
                'InitialLearnRate', learningRate, ...
                'ValidationData', {XVal, YVal}, ...
                'Shuffle', 'every-epoch',...
                'ValidationFrequency', floor(numWindows / (3 * options.hyperparameters.training.minibatchSize.value)), ...
                'OutputFcn', @(info) send(dataqueue, struct('experimentNumber', idx, 'info', info)));
        end
    case 'LSTM'
        learningRate = 0.001;
        if options.hyperparameters.training.ratioTrainVal.value == 1
            trainOptions = trainingOptions('adam', ...
                'MaxEpochs', options.hyperparameters.training.epochs.value, ...
                'MiniBatchSize', options.hyperparameters.training.minibatchSize.value, ...
                'InitialLearnRate', learningRate, ...
                'Shuffle', 'every-epoch',...
                'OutputFcn', @(info) send(dataqueue, struct('experimentNumber', idx, 'info', info)));
        else
            trainOptions = trainingOptions('adam', ...
                'MaxEpochs', options.hyperparameters.training.epochs.value, ...
                'MiniBatchSize', options.hyperparameters.training.minibatchSize.value, ...
                'InitialLearnRate', learningRate, ...
                'ValidationData', {XVal, YVal}, ...
                'Shuffle', 'every-epoch',...
                'ValidationFrequency', floor(numWindows / (3 * options.hyperparameters.training.minibatchSize.value)), ...
                'OutputFcn', @(info) send(dataqueue, struct('experimentNumber', idx, 'info', info)));
        end
    case 'Hybrid CNN-LSTM'
        learningRate = 0.001;
        if options.hyperparameters.training.ratioTrainVal.value == 1
            trainOptions = trainingOptions('adam', ...
                'MaxEpochs', options.hyperparameters.training.epochs.value, ...
                'GradientThreshold', 1, ...
                'InitialLearnRate', learningRate, ...
                'LearnRateSchedule', 'piecewise', ...
                'LearnRateDropPeriod', 96, ...
                'LearnRateDropFactor', 0.25, ...
                'MiniBatchSize', options.hyperparameters.training.minibatchSize.value,...
                'Verbose', false, ...
                'Shuffle', 'every-epoch',...
                'OutputFcn', @(info) send(dataqueue, struct('experimentNumber', idx, 'info', info)));
        else
            trainOptions = trainingOptions('adam', ...
                'MaxEpochs', options.hyperparameters.training.epochs.value, ...
                'GradientThreshold', 1, ...
                'InitialLearnRate', learningRate, ...
                'LearnRateSchedule', 'piecewise', ...
                'LearnRateDropPeriod', 96, ...
                'LearnRateDropFactor', 0.25, ...
                'MiniBatchSize', options.hyperparameters.training.minibatchSize.value,...
                'Verbose', false, ...
                'Shuffle', 'every-epoch',...
                'ValidationData', {XVal, YVal}, ...
                'ValidationFrequency', floor(numWindows / (3 * options.hyperparameters.training.minibatchSize.value)), ...
                'OutputFcn', @(info) send(dataqueue, struct('experimentNumber', idx, 'info', info)));
        end
    case 'GRU'
        learningRate = 0.001;
        if options.hyperparameters.training.ratioTrainVal.value == 1
            trainOptions = trainingOptions('adam', ...
                'MaxEpochs', options.hyperparameters.training.epochs.value, ...
                'MiniBatchSize', options.hyperparameters.training.minibatchSize.value, ...
                'InitialLearnRate', learningRate, ...
                'Shuffle', 'every-epoch',...
                'OutputFcn', @(info) send(dataqueue, struct('experimentNumber', idx, 'info', info)));
        else
            trainOptions = trainingOptions('adam', ...
                'MaxEpochs', options.hyperparameters.training.epochs.value, ...
                'MiniBatchSize', options.hyperparameters.training.minibatchSize.value, ...
                'InitialLearnRate', learningRate, ...
                'ValidationData', {XVal, YVal}, ...
                'Shuffle', 'every-epoch',...
                'ValidationFrequency', floor(numWindows / (3 * options.hyperparameters.training.minibatchSize.value)), ...
                'OutputFcn', @(info) send(dataqueue, struct('experimentNumber', idx, 'info', info)));
        end
    case 'CNN (DeepAnT)'
        learningRate = 0.001;
        if options.hyperparameters.training.ratioTrainVal.value == 1
            trainOptions = trainingOptions('adam', ...
                'MaxEpochs', options.hyperparameters.training.epochs.value, ...
                'GradientThreshold', 1, ...
                'InitialLearnRate', learningRate, ...
                'LearnRateSchedule', 'piecewise', ...
                'LearnRateDropPeriod', 96, ...
                'LearnRateDropFactor', 0.25, ...
                'MiniBatchSize', options.hyperparameters.training.minibatchSize.value,...
                'Verbose', false, ...
                'Shuffle', 'every-epoch',...
                'OutputFcn', @(info) send(dataqueue, struct('experimentNumber', idx, 'info', info)));
        else
            trainOptions = trainingOptions('adam', ...
                'MaxEpochs', options.hyperparameters.training.epochs.value, ...
                'GradientThreshold', 1, ...
                'InitialLearnRate', learningRate, ...
                'LearnRateSchedule', 'piecewise', ...
                'LearnRateDropPeriod', 96, ...
                'LearnRateDropFactor', 0.25, ...
                'MiniBatchSize', options.hyperparameters.training.minibatchSize.value,...
                'Verbose', false, ...
                'Shuffle', 'every-epoch',...
                'ValidationData', {XVal, YVal}, ...
                'ValidationFrequency', floor(numWindows / (3 * options.hyperparameters.training.minibatchSize.value)), ...
                'OutputFcn', @(info) send(dataqueue, struct('experimentNumber', idx, 'info', info)));
        end
    case 'ResNet'
        learningRate = 0.001;
        if options.hyperparameters.training.ratioTrainVal.value == 1
            trainOptions = trainingOptions('adam', ...
                'MaxEpochs', options.hyperparameters.training.epochs.value, ...
                'GradientThreshold', 1, ...
                'InitialLearnRate', learningRate, ...
                'LearnRateSchedule', 'piecewise', ...
                'LearnRateDropPeriod', 96, ...
                'LearnRateDropFactor', 0.25, ...
                'MiniBatchSize', options.hyperparameters.training.minibatchSize.value,...
                'Verbose', false, ...
                'Shuffle', 'every-epoch',...
                'OutputFcn', @(info) send(dataqueue, struct('experimentNumber', idx, 'info', info)));
        else
            trainOptions = trainingOptions('adam', ...
                'MaxEpochs', options.hyperparameters.training.epochs.value, ...
                'GradientThreshold', 1, ...
                'InitialLearnRate', learningRate, ...
                'LearnRateSchedule', 'piecewise', ...
                'LearnRateDropPeriod', 96, ...
                'LearnRateDropFactor', 0.25, ...
                'MiniBatchSize', options.hyperparameters.training.minibatchSize.value,...
                'Verbose', false, ...
                'Shuffle', 'every-epoch',...
                'ValidationData', {XVal, YVal}, ...
                'ValidationFrequency', floor(numWindows / (3 * options.hyperparameters.training.minibatchSize.value)), ...
                'OutputFcn', @(info) send(dataqueue, struct('experimentNumber', idx, 'info', info)));
        end
    case 'WaveNet'
        learningRate = 0.001;
        if options.hyperparameters.training.ratioTrainVal.value == 1
            trainOptions = trainingOptions('adam', ...
                'MaxEpochs', options.hyperparameters.training.epochs.value, ...
                'GradientThreshold', 1, ...
                'InitialLearnRate', learningRate, ...
                'LearnRateSchedule', 'piecewise', ...
                'LearnRateDropPeriod', 96, ...
                'LearnRateDropFactor', 0.25, ...
                'MiniBatchSize', options.hyperparameters.training.minibatchSize.value,...
                'Verbose', false, ...
                'Shuffle', 'every-epoch',...
                'OutputFcn', @(info) send(dataqueue, struct('experimentNumber', idx, 'info', info)));
        else
            trainOptions = trainingOptions('adam', ...
                'MaxEpochs', options.hyperparameters.training.epochs.value, ...
                'GradientThreshold', 1, ...
                'InitialLearnRate', learningRate, ...
                'LearnRateSchedule', 'piecewise', ...
                'LearnRateDropPeriod', 96, ...
                'LearnRateDropFactor', 0.25, ...
                'MiniBatchSize', options.hyperparameters.training.minibatchSize.value,...
                'Verbose', false, ...
                'Shuffle', 'every-epoch',...
                'ValidationData', {XVal, YVal}, ...
                'ValidationFrequency', floor(numWindows / (3 * options.hyperparameters.training.minibatchSize.value)), ...
                'OutputFcn', @(info) send(dataqueue, struct('experimentNumber', idx, 'info', info)));
        end
    case 'MLP'
        learningRate = 0.001;
        if options.hyperparameters.training.ratioTrainVal.value == 1
            trainOptions = trainingOptions('adam', ...
                'MaxEpochs', options.hyperparameters.training.epochs.value, ...
                'GradientThreshold', 1, ...
                'InitialLearnRate', learningRate, ...
                'LearnRateSchedule', 'piecewise', ...
                'LearnRateDropPeriod', 96, ...
                'LearnRateDropFactor', 0.25, ...
                'MiniBatchSize', options.hyperparameters.training.minibatchSize.value,...
                'Verbose', false, ...
                'Shuffle', 'every-epoch',...
                'OutputFcn', @(info) send(dataqueue, struct('experimentNumber', idx, 'info', info)));
        else
            trainOptions = trainingOptions('adam', ...
                'MaxEpochs', options.hyperparameters.training.epochs.value, ...
                'GradientThreshold', 1, ...
                'InitialLearnRate', learningRate, ...
                'LearnRateSchedule', 'piecewise', ...
                'LearnRateDropPeriod', 96, ...
                'LearnRateDropFactor', 0.25, ...
                'MiniBatchSize', options.hyperparameters.training.minibatchSize.value,...
                'Verbose', false, ...
                'Shuffle', 'every-epoch',...
                'ValidationData', {XVal, YVal}, ...
                'ValidationFrequency', floor(numWindows / (3 * options.hyperparameters.training.minibatchSize.value)), ...
                'OutputFcn', @(info) send(dataqueue, struct('experimentNumber', idx, 'info', info)));
        end
end
end
