function trainOptions = getOptions(options, XVal, YVal, numWindows, plots)
%GETOPTIONS
%
% Returns the training options for training of DL models

if gpuDeviceCount > 0
    device = 'gpu';
else
    device = 'cpu';
end

switch options.model
    case 'Your model'
    otherwise
        if options.hyperparameters.ratioTrainVal.value == 0
            trainOptions = trainingOptions('adam', ...
                'Plots', plots, ...
                'MaxEpochs', options.hyperparameters.epochs.value, ...
                'MiniBatchSize', options.hyperparameters.minibatchSize.value, ...
                'GradientThreshold', 1, ...
                'InitialLearnRate', options.hyperparameters.learningRate.value, ...
                'Shuffle', 'every-epoch',...
                'ExecutionEnvironment', device);
        else
            trainOptions = trainingOptions('adam', ...
                'Plots', plots, ...
                'MaxEpochs', options.hyperparameters.epochs.value, ...
                'MiniBatchSize', options.hyperparameters.minibatchSize.value, ...
                'GradientThreshold', 1, ...
                'InitialLearnRate', options.hyperparameters.learningRate.value, ...
                'Shuffle', 'every-epoch', ...
                'ExecutionEnvironment', device, ...
                'ValidationData', {XVal, YVal}, ...
                'ValidationFrequency', floor(numWindows / (3 * options.hyperparameters.minibatchSize.value)));
        end
end
end
