function trainOptions = getOptionsForParallel(options, XVal, YVal, numWindows, dataqueue, idx)
%GETOPTIONSFORPARALLEL
%
% Returns the training options for parallel training of DL models

if gpuDeviceCount > 0
    device = 'gpu';
else
    device = 'cpu';
end

switch options.model
    case 'Your model'
    otherwise
        if options.hyperparameters.ratioTrainVal.value == 0
            trainOptions = trainingOptions('adam', ...
                'MaxEpochs', options.hyperparameters.epochs.value, ...
                'MiniBatchSize', options.hyperparameters.minibatchSize.value, ...
                'GradientThreshold', 1, ...
                'InitialLearnRate', options.hyperparameters.learningRate.value, ...
                'Shuffle', 'every-epoch', ...
                'ExecutionEnvironment', device, ...
                'OutputFcn', @(info) send(dataqueue, struct('experimentNumber', idx, 'info', info)));
        else
            trainOptions = trainingOptions('adam', ...
                'MaxEpochs', options.hyperparameters.epochs.value, ...
                'MiniBatchSize', options.hyperparameters.minibatchSize.value, ...
                'GradientThreshold', 1, ...
                'InitialLearnRate', options.hyperparameters.learningRate.value, ...
                'Shuffle', 'every-epoch', ...
                'ExecutionEnvironment', device, ...
                'ValidationData', {XVal, YVal}, ...
                'ValidationFrequency', floor(numWindows / (3 * options.hyperparameters.minibatchSize.value)), ...
                'OutputFcn', @(info) send(dataqueue, struct('experimentNumber', idx, 'info', info)));
        end
end
end
