function scores = computeMetrics(anomalyScores, predictedLabels, labels)
%COMPUTEMETRICS Calculates the different metrics

% Pointwise scores
[pre_p, rec_p, f1_score_p, f05_score_p] = computePointwiseMetrics(predictedLabels, labels);

% Eventwise scores
[pre_e, rec_e, f1_score_e, f05_score_e] = computeEventwiseMetrics(predictedLabels, labels);

% Point-adjusted scores
[pre_pa, rec_pa, f1_score_pa, f05_score_pa] = computePointAdjustedMetrics(predictedLabels, labels);

% Composite scores (combine point-wise precision and event-wise recall)
[f1_score_c, f05_score_c] = computeCompositeMetrics(predictedLabels, labels);

% AUC
try
    % Calc AUC. (If model outputs labels then anomalyScores == predictedLabels)
    [~, ~, ~, AUC] = perfcurve(labels, anomalyScores, 1);
catch
    AUC = NaN;
end

% The order of scores must be the same as in the METRIC_NAMES... files.
scores = [f1_score_p; ...
          f1_score_e; ...
          f1_score_pa; ...
          f1_score_c; ...
          f05_score_p; ...
          f05_score_e; ...
          f05_score_pa; ...
          f05_score_c; ...
          pre_p; ...
          pre_e; ...
          pre_pa; ...
          rec_p; ...
          rec_e; ...
          rec_pa; ...
          AUC];

scores = round(scores, 4); % Round do 4 decimal places
end
