function metricNames = METRIC_NAMES_WITH_COMP_TIME()
%METRIC_NAMES_WITH_COMP_TIME Returns all metric names used by the tsad
%platform includeing the computation time

metricNames = ["Mean Computation Time per Window (Seconds)"; ...
                "F1 Score (pointwise)"; ...
                "F1 Score (eventwise)"; ...
                "F1 Score (pointadjusted)"; ...
                "F1 Score (composite)"; ...
                "F0.5 Score (pointwise)"; ...
                "F0.5 Score (eventwise)"; ...
                "F0.5 Score (pointadjusted)"; ...
                "F0.5 Score (composite)"; ...
                "Precision (pointwise)"; ...
                "Precision (eventwise)"; ...
                "Precision (pointadjusted)"; ...
                "Recall (pointwise)"; ...
                "Recall (eventwise)"; ...
                "Recall (pointadjusted)"; ...
                "AUC"];
end