function metricNames = METRIC_NAMES()
%METRIC_NAMES Returns all metric names used by the tsad platform

metricNames = ["F1 Score (pointwise)"; ...
                "F1 Score (eventwise)"; ...
                "F1 Score (pointadjusted)"; ...
                "F1 Score (composite)"; ...
                "F0.5 Score (pointwise)"; ...
                "F0.5 Score (eventwise)"; ...
                "F0.5 Score (pointadjusted)"; ...
                "F0.5 Score (composite)"; ...
                "Precision (pointwise)"; ...
                "Precision (eventwise)"; ...
                "Precision (pointadjusted)"; ...
                "Recall (pointwise)"; ...
                "Recall (eventwise)"; ...
                "Recall (pointadjusted)"; ...
                "AUC"];
end