function [XTrain, YTrain, XVal, YVal] = prepareDataTrain_DNN(modelOptions, data, labels)
%PREPAREDATATRAIN_DNN Prepares the training data for DNN models

switch modelOptions.name
    case 'Your model name'
    otherwise
        [XTrain, YTrain, XVal, YVal] = splitDataTrain(data, ...
            modelOptions.hyperparameters.windowSize.value, ...
            modelOptions.hyperparameters.stepSize.value,  ...
            modelOptions.hyperparameters.ratioTrainVal.value, ...
            modelOptions.modelType, modelOptions.dataType);
end
end