function [XTrain, YTrain, XVal, YVal] = prepareDataTrain_DL(modelOptions, data, labels)
%PREPAREDATATRAIN_DNN Prepares the training data for DNN models

switch modelOptions.name
    case "Your model name"
    otherwise
        [XTrain, YTrain, XVal, YVal] = splitDataTrain(data, ...
            modelOptions.hyperparameters.windowSize, ...
            modelOptions.hyperparameters.stepSize,  ...
            modelOptions.hyperparameters.ratioTrainVal, ...
            modelOptions.modelType, modelOptions.dataType);
end
end